{
 "title": "K8S Cluster Health",
 "description": "Dashboard to get an overview of K8S Production Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Master Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API server is Alive?",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"kubernetes\",svc_component=\"apiserver\"})",
     "legendFormat": "Number of API Servers"
    }
   ]
  },
  {
   "title": "API Servers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"kubernetes\", svc_component=\"apiserver\"})",
     "legendFormat": "Number of API Servers"
    }
   ]
  },
  {
   "title": "API [rpm]",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[1m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "API Server Request Error %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum by(instance) (rate(apiserver_request_count{code=~\"5..\"}[5m])) / sum by(instance) (rate(apiserver_request_count[5m]))) * 100",
     "legendFormat": "Number of API Servers"
    }
   ]
  },
  {
   "title": "[API] Failed Requests [opm]",
   "type": "graph",
   "description": "[rate 1m] [opm]",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ops/m" }
   ],
   "targets": [
    {
     "expr": "max(changes(apiserver_request_count{code=~\"5..\"}[1m])) by (code,verb,client,resource) > 0",
     "legendFormat": "{{resource}} / {{verb}} / {{client}} / {{code}} "
    }
   ]
  },
  {
   "title": "ETCD is alive?",
   "type": "singlestat",
   "description": "The metric (\"etcd_server_has_leader\") checks if our ETCD instance is responding, at least 1",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "ETCD Servers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"etcd-servers\"})",
     "legendFormat": "Number of API Servers"
    }
   ]
  },
  {
   "title": "ETCD [rps]",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\",container_name=\"etcd-container\"}[5m]))"
    }
   ]
  },
  {
   "title": "ETCD Server Request Error %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\",container_name=\"etcd-container\"}[5m])) * 100 ",
     "legendFormat": "Number of API Servers"
    }
   ]
  },
  {
   "title": "[ETCD] FAILED Requests [ops]",
   "type": "graph",
   "description": "[rate 1m] [ops]",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "ops", "label": "Ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\",container_name=\"etcd-container\"}[5m])) by (pod_name, grpc_code)",
     "legendFormat": "{{pod_name}} / {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Autoscaler is alive?",
     "type": "singlestat",
     "description": "cluster_safe_to_autoscale indicates whether cluster is healthy enough for autoscaling. CA stops all operations if significant number of nodes are unready (by default 33% as of CA 0.5.4).",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_cluster_safe_to_autoscale)"
      }
     ]
    },
    {
     "title": "Kube Scheduler is  alive?",
     "type": "singlestat",
     "description": "he Kubernetes scheduler is a policy-rich, topology-aware, workload-specific function that significantly impacts availability, performance, and capacity. The scheduler needs to take into account individual and collective resource requirements, quality of service requirements, hardware/software/policy constraints, affinity and anti-affinity specifications, data locality, inter-workload interference, deadlines, and so on. Workload-specific requirements will be exposed through the API as necessary.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(up{job=\"kube-scheduler\", pod_k8s_app=\"kube-scheduler\"})",
       "target": "averageSeries(worldping.prod_vivareal_io.sao-paulo.https.ok_state)"
      }
     ]
    },
    {
     "title": "Controller Manager is alive?",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(up{job=\"kube-controller-manager\"}))"
      }
     ]
    },
    {
     "title": "Metrics Server is alive?",
     "type": "singlestat",
     "description": "Metrics Server is responsible for cluster basic metrics like CPU, RAM and Network.\nAlso responsible for services like cluster-autoscaler, hpa and kubernetes dashboard to work.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_deployment_spec_replicas{deployment=\"metrics-server\",pod=~\"kube-state-metrics-(.*)\"})"
      }
     ]
    },
    {
     "title": "Prometheus is alive?",
     "type": "singlestat",
     "description": "Prometheus Server is responsible for you to see all this metrics in this dashboards :D",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(up{job=\"prometheus-v2\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Nodes",
     "type": "singlestat",
     "description": "Nodes  and Masters with status (\"Ready\") in cluster.",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\"})"
      }
     ]
    },
    {
     "title": "Nodes Available",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\"})/sum(cluster_autoscaler_nodes_count)*100"
      }
     ]
    },
    {
     "title": "Unready Nodes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 19 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_nodes_count{state=\"unready\"})"
      }
     ]
    },
    {
     "title": "Running PODS",
     "type": "singlestat",
     "description": "Pods with state (\"Running\") in our cluster.",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",pod=~\"kube-state-metrics-(.*)\"})"
      }
     ]
    },
    {
     "title": "Pending Pods",
     "type": "singlestat",
     "description": "Number of unschedulable (\"Pending\") pods in the cluster.",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 19 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_unschedulable_pods_count)",
       "legendFormat": "Unschedulable Pods"
      }
     ]
    },
    {
     "title": "Cluster Direction",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(cluster_autoscaler_scaled_up_nodes_total)-sum(cluster_autoscaler_scaled_down_nodes_total)"
      }
     ]
    },
    {
     "title": "CPU Requests Total",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance)) * 100"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "1 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))"
      }
     ]
    },
    {
     "title": "Memory Requests Total",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance)) * 100"
      }
     ]
    },
    {
     "title": "Pods Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "((sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes)) * 100"
      }
     ]
    }
   ]
  },
  { "title": "Ingress Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "[Ingress] Throughput [rpm]",
   "type": "graph",
   "description": "[rate 1m] [rpm]",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "req/m" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests[1m])) by (status) > 0 ",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "[Ingress] Nginx Connections",
   "type": "graph",
   "description": "Ingress Nginx'es connection types",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_connections_total[1m])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "2xx [rpm]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"2.*\"}[1m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "3xx [rpm]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"3.*\"}[1m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "4xx [rpm]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"4.*\"}[1m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "5xx [rpm]",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{status=~\"5.*\"}[1m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  {
   "title": "RPM Total",
   "type": "singlestat",
   "description": "All Status Code",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "RPM"
    }
   ]
  },
  { "title": "Cronjobs Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Active CronJobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none", "label": "Active Jobs" }
   ],
   "targets": [
    {
     "expr": "sum(kube_cronjob_status_active) by (cronjob, exported_namespace)",
     "legendFormat": "{{exported_namespace}}/{{cronjob}}"
    }
   ]
  },
  {
   "title": "Active CronJobs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_cronjob_status_active)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 35, "w": 24, "x": 0, "y": 22 } }
   ]
  }
 ]
}