apiVersion: v1
kind: Service
metadata:
  name: domain-kube-etcd-events
  labels:
    app: domain-kube-etcd-events
    jobLabel: kube-etcd-events
    chart: prometheus-operator-5.0.13
    release: domain-monitoring
    heritage: "Tiller"
    expose: "true"
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 4002
      protocol: TCP
      targetPort: 4002
  selector:
    k8s-app: etcd-server-events

  type: ClusterIP