apiVersion: v1
kind: ServiceAccount
metadata:
  name: domain-monitoring
  labels:
    app: prometheus-operator-alertmanager
    chart: prometheus-operator-5.0.13
    release: "operatic-mouse"
    heritage: "Tiller"

 
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: domain-monitoring-cluster-role
  labels:
    app: prometheus-operator-operator
    
    chart: prometheus-operator-5.0.13
    release: "operatic-mouse"
    heritage: "Tiller"
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - prometheuses/finalizers
  - alertmanagers/finalizers
  - servicemonitors
  - prometheusrules
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: domain-monitoring-role-binding
  labels:
    app: prometheus-operator-operator
    chart: prometheus-operator-5.0.13
    release: "operatic-mouse"
    heritage: "Tiller"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: domain-monitoring-cluster-role
subjects:
- kind: ServiceAccount
  name: domain-monitoring
  namespace: monitoring
